server:
  port: ${PORT:8080}   # Render가 자동으로 PORT 환경변수를 주입

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate   # 테이블 자동수정 방지
    show-sql: false