package com.example.backend.entity.enums;

public enum Language {
    KOREAN, ENGLISH, VIETNAMESE, CHINESE, MYANMARESE, JAPANESE, INDONESIAN, MALAYSIAN, ARABIC, FRENCH, GERMAN, SPANISH, RUSSIAN, HINDI, OTHER
}
