package com.example.backend.entity.enums;

public enum Nationality {
    ALGERIAN, AMERICAN, ARGENTINIAN, AUSTRALIAN, AZERBAIJANI, BANGLADESHI, BELARUSIAN, BELGIAN, BRAZILIAN, BRITISH, CAMBODIAN, CANADIAN, CHILEAN, CHINESE, COLOMBIAN, CUBAN, CZECH, DUTCH, ECUADORIAN, EGYPTIAN, EMIRATI, ETHIOPIAN, FILIPINO, FINNISH, FRENCH, GEORGIAN, GERMAN, GHANAIAN, GREEK, HUNGARIAN, INDIAN, INDONESIAN, IRANIAN, IRAQI, ITALIAN, JAMAICAN, JAPANESE, JORDANIAN, KAZAKHSTANI, KENYAN, KOREAN, KYRGYZ, LAOTIAN, LEBANESE, MALAYSIAN, MEXICAN, MONGOLIAN, MOROCCAN, MYANMARESE, NEPALESE, NEW_ZEALANDER, NIGERIAN, NORWEGIAN, PAKISTANI, PALESTINIAN, PERUVIAN, POLISH, PORTUGUESE, QATARI, ROMANIAN, RUSSIAN, SAUDI, SINGAPOREAN, SOUTH_AFRICAN, SPANISH, SRI_LANKAN, SUDANESE, SWEDISH, TAIWANESE, THAI, TURKISH, UKRAINIAN, UZBEKISTANI, VENEZUELAN, VIETNAMESE, YEMENI, NONE
}
