name: Backend CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: backend-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Temurin JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: 'gradle'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build (compile + test)
        run: ./gradlew build --no-daemon

      - name: Upload test report (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-reports
          path: |
            backend/build/test-results/test
            backend/build/reports/tests/test
          if-no-files-found: ignore