name: Backend CI

on:
  push: { branches: [ "**" ] }
  pull_request: { branches: [ "**" ] }
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Show workspace
        run: pwd && ls -la

      - name: Set up Temurin JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: 'gradle'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build (compile + test)
        run: ./gradlew build --no-daemon

      - name: Upload test report (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-reports
          path: |
            build/test-results/test
            build/reports/tests/test
          if-no-files-found: ignore
